### ISSUE TITLE
Add simple mechanism to see the explain plan for a query

### ISSUE THREAD

**Issue by tremechus** [tremechus/sqlboa#4]
Add simple mechanism to see the explain plan for a query.  Perhaps a context menu on the tab, or additional button next to the Refresh icon

**Comment by tcroft** [comment]
User can CTRL-E while on a table name to get the table definition or CTRL-E on  a sql keyword (like 'select') to get the query plan

**Comment by tremechus** [comment]
Added CTRL-E to sheet hotkeys, when cursor is on a table name will describe table, if on a sql keyword (like 'select') will give explain plan
